version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
build_script:
- pwsh: nuget pack IntelliTect.Coalesce.Vue.Template.nuspec -Version $env:APPVEYOR_REPO_TAG_NAME
test: off
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: fTeCz7vCf9pnihG4nFAIP2QCwfECOUzPLSA5pGFXgZCWuJLnYX0aoC5LLYAXTpaK
